/*
Arquivo: prisma.config.ts
Objetivo: Configuracao de ambiente para Prisma.
Guia rapido: consulte imports no topo, depois tipos/constantes, e por fim a exportacao principal.
*/

// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // URL opcional - permite build sem DATABASE_URL configurada
    url: process.env.DATABASE_URL || "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});

